services:
  db:
    image: postgres:17-alpine
    container_name: throw_poll_db
    environment:
      POSTGRES_DB: throw_poll
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: