services:
  db:
    image: postgres:17-alpine
    container_name: pop_poll_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: pop_poll_redis
    command: ["redis-server",
      "--requirepass", "${REDIS_PASSWORD}",  
      "--appendonly", "yes",
      "--appendfilename", "appendonly.aof",
      "--dir", "/data"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  pgdata:
  redisdata: